### ISSUE TITLE
configs missing in vbcc formula

### ISSUE THREAD

**Issue by cnvogelg** [tditlu/homebrew-amiga#3]
Kudos for the vbcc homebrew formula - its greatly appreciated!

However, I need to manually add the config files of vbcc to get a useable setup.
Config files are found here: [vbcc_unix_config.tar.gz](http://server.owl.de/~frank/vbcc/2017-08-14/vbcc_unix_config.tar.gz) and are stored in `$VBCC/config`
With these files in place you can select the config with
`vc +aos68k ...`

It would be great if you could add the installation of the config to the vbcc formula...

**Comment by tditlu** [comment]
Thank you for reporting, it's added now:
[](https://github.com/tditlu/homebrew-amiga/commit/b358f5d029c36c578365fdd3daa144e5caf038a0)

**Comment by cnvogelg** [comment]
works like a charm. Thanks!
