### ISSUE TITLE
Update vbcc, vasm, vlink to recent release

### ISSUE THREAD

**Issue by cnvogelg** [tditlu/homebrew-amiga#4]
Hi,

it would be great if you could update the formulas to the recent release versions:

- vbcc: 0.9g (4.10.2019)
- vasm:  1.8g (4.10.2019)
- vlink: 0.16c (10.7.2019)

Thanks a lot!

**Comment by tditlu** [comment]
Done & thanks!
Will find some way to automate this or at least make a script that notify me when there's a new version.
